### PR TITLE
Reminder on First Annotation

### PR DESCRIPTION
**Pull request by wgranger**
Per suggestion in #188, this PR adds a reminder to the user when making a first annotation. After the reminder is seen, a tag is saved in the user preferences.

### CODE REVIEW

**Comment by snblickhan** [comment]
@beckyrother Do you think it's worth keeping this reminder if we're going to endpoint dot annotation? My vote would be yes, but I'm curious to know what you think.

**Comment by beckyrother** [comment]
Yes, I think it's still useful, especially as we're changing the way this works.

**Comment by shaunanoordin** [comment]
Quick check: do we still need this Reminder on the First Annotation popup? If yes, there's a bit of merging and/or rebasing that I should get on.

**Comment by wgranger** [comment]
Ooo. Didn't notice that rebase needed until you point it out. I believe we still need this. I'll put a post in the channel.

**Comment by shaunanoordin** [comment]
Quick thoughts:
- I've confirmed that the reminder appears properly for a non-logged-in user, but testing for a registered user has been an issue due to the saved preferences. All said, I'm happy enough with the implementation.
- Visual design looks good. 👍  Was going to write a report about it looking bad but then I remembered that when switching to a new branch, new stylesheets aren't incorporated until you restart the dev server. Derp.

**Comment by snblickhan** [comment]
@shaunanoordin Apologies -- I updated this modal text over in the Second Beta Prep thread a few days ago, as Tom Blake wanted a tutorial update about words split across two lines. I tagged Will & Becky, but not you, so this is 100% on me. Any way we can add the additional text (shown in bold below)?

> To create a new transcription, click below the start of a line of text just before the first word, and again just after the last word. This will underline the text you wish to transcribe. Please annotate and transcribe entire lines at a time. **Words split between two lines should be typed out in their entirety on the first line.** If you're unsure of anything, please revisit the project tutorial.

**Comment by wgranger** [comment]
Sure. This can be done easily. @snblickhan

**Pull request merged**
