### PR TITLE
Create Maintenance Message

### PR DESCRIPTION
**Pull request by wgranger**
Creates a quick maintenance message on the home screen based on a [PR](https://github.com/zooniverse/Panoptes-Front-End/pull/5770) by @shaunanoordin.

Screen Shot 2020-07-21 at 9 05 15 AM

### CODE REVIEW

**Comment by shaunanoordin** [comment]
As we're going into maintenance mode in about 5 minutes, this branch has been deployed without merging.

**Comment by shaunanoordin** [comment]
This branch has fulfilled its purpose.

**Comment by shaunanoordin** [comment]
Wait, there's another downtime planned for Wednesday 28 Jul 2020, 9am BST.

I CAST RESURRECT BRANCH!

**Comment by wgranger** [comment]
Closing this since maintenance is over, but I'll keep the branch handy.

**Pull request closed without merging**
