### PR TITLE
Add Keyboard Shortcuts

### LINKED ISSUE #172: Add Keyboard Shortcuts
This will help improve accessibility #107, and will also help the overall functionality of the site. Upon initial conversation, keyboard shortcuts can be added in the classifier for:

- Toggle previous marks
- Toggle between navigate/annotate

### PR DESCRIPTION
**Pull request by wgranger**
This includes four keyboard shortcuts as well as a descriptive popup to notify the user what the shortcuts are.

There are also some line changes to make items agree with the linter (the bulk of the changes)

Closes #172

### CODE REVIEW

**Comment by shaunanoordin** [comment]
Confirmed: **Ctrl+N** opens a new window on most browsers (Chrome, FF, IE11) on Windows machines.

**Ctrl+M** seems safe?

Here's a list of common browser shortcuts - https://www.howtogeek.com/114518/47-keyboard-shortcuts-that-work-in-all-web-browsers/ - so it should give us an advantage in figuring out what to avoid.

**Comment by shaunanoordin** [comment]
DERP! I forgot that Esc is a common key for stopping the page from loading - but that's fine and I'm strongly in favour of _keeping the Esc as is._ The Esc key is a very, very sensible, multipurpose key that's OK to be overloaded.

Besides, once the website has loaded, the Esc key doesn't stop any further data fetches, so it looks like we're good.

**Comment by wgranger** [comment]
Thanks for the thorough review on this. You caught some items that would've caused issues in the future. I've changed switching between annotate/navigate to ctrl + a. A is for 'annotate.'

**Comment by snblickhan** [comment]
Priority for beta 2

**Comment by shaunanoordin** [comment]
This PR _may_ need to be rebased after #198 is merged; IIRC there are some notable changes to... `SelectedAnnotation`, I think, that reflects how we no longer need to check for word count. I'll look into this one 198 is out of the way.

Also, we need another option for the Annotate shortcut unfortunately, as Ctrl+A in Windows means "select all", and will cause the whole page to be highlighted.

**Comment by wgranger** [comment]
About the make the changes mentioned above. Also @beckyrother did we at some point discuss (in Slack possibly?) using cmd in the case of a Mac? Or also ctrl? Both? There is a metakey as mentioned in the link.
 (https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/metaKey)

**Comment by beckyrother** [comment]
We had talked about simply using the letter keys without a modifier (so `a` for annotate, etc). Looking at gmail as a model. 

Here's a good Medium post about single-letter keyboard shortcuts, for reference: https://medium.com/@sashika/j-k-or-how-to-choose-keyboard-shortcuts-for-web-applications-a7c3b7b408ee

**Comment by shaunanoordin** [comment]
Now that #198 has been merged, I'm looking at conflict resolution at the moment - let's see if we can do this without a rebase.

**Comment by shaunanoordin** [comment]
Testing ongoing: I need to see what 'Enter' does when the text is empty. (I can't think of other 'invalid' states.)

**Comment by beckyrother** [comment]
Enter shouldn't do anything when the text is empty. Maybe 'esc' closes the box?

**Comment by shaunanoordin** [comment]
@beckyrother Right, so I just merged the latest changes from the master (the Single Line Annotation stuff) to this PR and everything's compatible. Let's talk expected vs actual behaviour. 👌 

Right now, when the text is empty and you click Done _or_ Press Enter, the app goes "Look, I'm assuming you're saying the Line of Text is empty (no words), so let's just delete that Line."

Full details:
- When the user marks the start and end of a _new_ Line of Text, the Transcription dialog auto-opens...
  - If the user types nothing `""` and clicks Close/presses Esc, the new Line is deleted.
  - If the user types nothing `""` and clicks Done/presses Enter, the new Line is deleted. 👀
  - If the user types something `"tralala"` and clicks Close/presses Esc, the new Line is deleted. 👀
  - If the user types something `"tralala"` and clicks Done/presses Enter, the new Line is saved & updated.
- When the user clicks on an _existing_ Line of Text, the Transcription dialog opens...
  - If the user clicks Close/presses Esc, the Line is unchanged.
  - If the user makes changes (where the text is NOT empty) `"trololo"` and clicks Done/presses Enter, the Line is updated.
  - If the user _deletes the text_ `""` and clicks Done/presses Enter, the Line is deleted. 👀

Most of these conditions are pretty straightforward/expected, but the conditions marked with 👀  are probably the ones you need to stare at and rub your chin thoughtfully at before giving a 👍  or 👎 

That said, it may make more sense for me to 👍  this PR, merge it, and deploy it so you can see the changes in action. This PR is stable enough for a release. @wgranger Any issues with this? (EDIT: Wait, do we have staging? I vaguely remember that, or it might have been a Christmas dream.)

**Comment by shaunanoordin** [comment]
## PR Review (Update)
As mentioned, I'm going to 👍  and merge this PR. The changes themselves are stable enough to deploy, and I'd like to get these changes out to production so the team can see the UI/UX changes in action.

### Status
PR is stable _enough._ Merging, deploying to production, with the expectation that further updates/tweaks (e.g. we still haven't resolved that Ctrl+A shortcut) will need to be introduced.

**Comment by shaunanoordin** [comment]
Wait... I need to get a sanity check on this. I'm proposing a deploy to production on a Friday afternoon. Taking this to #imls on Slack.

**Pull request merged**
